Repository YAPP-Github/Reed-iOS, pull requests merged in 2025-08, with the labels that each got.

#124 feat: 감상평 가이드 추가
  src/Projects/BKDesign/Sources/Components/BKPageControl.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/BKBottomSheetViewController.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Extension/BKBottomSheetViewController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/AppreciationGuideButton.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceAppreciationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteForm.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteViewModel.swift
Labels: ✨ feat

#129 feat: 도서 상세 화면 구현
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/empty.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/empty.imageset/empty.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/empty.imageset/empty@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/empty.imageset/empty@3x.png
  src/Projects/BKDesign/Sources/Components/Summary/BKBookSummaryView.swift
  src/Projects/BKDesign/Sources/Extensions/UIColor+.swift
  src/Projects/BKDesign/Sources/Foundation/ColorSystem/BKSemanticColor.swift
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKImage.swift
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKInset.swift
  src/Projects/BKDomain/Sources/Entity/Book.swift
  src/Projects/BKPresentation/Sources/Common/Extension/BKBottomSheetViewController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/Coordinator/BookDetailCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailViewCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailViewHeader.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/SeedReportView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/ViewModel/BookDetailViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Extension/BKBottomSheetViewController+.swift
Labels: ✨ feat

#133 feat: home UI 개발
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/homeCharacter.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/homeCharacter.imageset/image@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/homeCharacter.imageset/image@3x.png
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKImage.swift
  src/Projects/BKPresentation/Sources/Common/Extension/UINavigationController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/GoToSearchView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeCardCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/RealHomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/RecordCountView.swift
Labels: ✨ feat

#134 feat: 1차 API 연결
  src/Projects/BKData/Sources/API/RecordAPI.swift
  src/Projects/BKData/Sources/DTO/Request/FetchRecordRequestDTO.swift
  src/Projects/BKData/Sources/DTO/Request/InsertRecordRequestDTO.swift
  src/Projects/BKData/Sources/DTO/Response/FetchRecordResponseDTO.swift
  src/Projects/BKData/Sources/DTO/Response/InsertRecordResponseDTO.swift
  src/Projects/BKData/Sources/DataAssembly.swift
  src/Projects/BKData/Sources/Repository/DefaultBookRepository.swift
  src/Projects/BKData/Sources/Repository/DefaultRecordRepository.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextFieldView.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextView.swift
  src/Projects/BKDomain/Sources/DomainAssembly.swift
  src/Projects/BKDomain/Sources/Entity/BookInfo.swift
  src/Projects/BKDomain/Sources/Entity/RecordInfo.swift
  src/Projects/BKDomain/Sources/Interface/Repository/RecordRepository.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/BookUpsertUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/CheckTermsStateUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/CreateRecordUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultBookUpsertUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultCreateRecordUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultSearchBookUseCase.swift
  src/Projects/BKDomain/Sources/VO/BookStatus.swift
  src/Projects/BKDomain/Sources/VO/LibraryDetails/LibrarySortType.swift
  src/Projects/BKDomain/Sources/VO/RecordDetails/RecordSortType.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/SeedReportView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/ViewModel/BookDetailViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Coordinator/NoteCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/EmotionRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceAppreciationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteForm.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/AppreciationResultView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/NoteCompletionView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/Coordinator/SearchCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/VO/BookRegistrationStatus.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/BookRegistrationStatusView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/ViewModel/SearchViewModel.swift
Labels: ✨ feat

#138 fix: 하단 탭바 아이콘 변경 및 vertical 포지션 변경
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/book.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/book@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/book@3x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/icon_24_folder.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/icon_24_folder@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/folder.imageset/icon_24_folder@3x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/home1.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/home@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/home@3x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/icon-home.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/icon-home@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/home.imageset/icon-home@3x.png
  src/Projects/BKPresentation/Sources/TabBarFlow/BottomTabBarController.swift
Labels: 🐞 fix

#147 feat: 애플 로그인 확장 및 변경사항 반영
  src/Projects/BKData/Sources/API/AuthAPI.swift
  src/Projects/BKData/Sources/API/UserAPI.swift
  src/Projects/BKData/Sources/DTO/Request/AuthLoginRequestDTO.swift
  src/Projects/BKData/Sources/Repository/DefaultAuthRepository.swift
  src/Projects/BKData/Sources/Repository/DefaultAuthStateRepository.swift
  src/Projects/BKData/Sources/Service/AppleLoginDelegateProxy.swift
  src/Projects/BKData/Sources/Service/AppleLoginService.swift
  src/Projects/BKData/Sources/Service/KakaoLoginService.swift
  src/Projects/BKDomain/Sources/Entity/SocialLoginToken.swift
  src/Projects/BKDomain/Sources/Interface/Repository/AuthRepository.swift
  src/Projects/BKDomain/Sources/Interface/SocialLoginService.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SocialLoginUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SocialTokenAuthUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultAuthenticationWithSocialTokenUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultSocialLoginUseCase.swift
  src/Projects/BKPresentation/Sources/AuthFlow/ViewModel/LoginViewModel.swift
Labels: ✨ feat

#151 feat: 로딩 인디케이터 추가
  src/Projects/BKDesign/Sources/Components/BKLoading/BKLoadingIndicator.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/LoginViewController.swift
  src/Projects/BKPresentation/Sources/AuthFlow/ViewModel/LoginViewModel.swift
Labels: ✨ feat

#166 fix: QA 항목 반영
  src/Projects/BKData/Sources/API/RecordAPI.swift
  src/Projects/BKDesign/Resources/Assets.xcassets/Logos/bigLogo.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteCompleted.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteCompleted@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteCompleted@3x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteimage.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteimage@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/noteCompleted.imageset/noteimage@3x.png
  src/Projects/BKDesign/Sources/Foundation/ColorSystem/BKSemanticColor.swift
  src/Projects/BKPresentation/Sources/AppCoordinator.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/LoginView.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/SplashView.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/SplashViewController.swift
  src/Projects/BKPresentation/Sources/Common/Extension/BKBottomSheetViewController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/Coordinator/BookDetailCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/SeedReportView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/ViewModel/BookDetailViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/View/HomeEmptyView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Coordinator/NoteCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/EmotionRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/OCRScannerViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/AppreciationResultView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/NoteCompletionViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/ViewModel/NoteCompletionViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchResultCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/ViewModel/SearchViewModel.swift
  src/Projects/Booket/Resources/LaunchScreen.storyboard
  src/SupportingFiles/Booket/Info.plist
Labels: 🐞 fix

#172 feat: firebase crashlytics 추가
  .gitignore
  src/Projects/Booket/Project.swift
  src/Projects/Booket/Sources/AppDelegate.swift
  src/Tuist/Package.resolved
  src/Tuist/Package.swift
  src/Tuist/ProjectDescriptionHelpers/SwiftLintScript.swift
  src/Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feat

#178 refactor: 릴리즈 타겟 추가 및 모듈 의존성 분리
  .github/workflows/ios_ci.yml
  src/Projects/BKCore/Project.swift
  src/Projects/BKCore/Sources/Logger/AppLogger.swift
  src/Projects/BKCore/Sources/Logger/DebugLogger.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/View/HomeView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/OCRScannerViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/RecognizedTextViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/OCRScannerViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/ViewModel/SearchViewModel.swift
  src/Projects/Booket/Project.swift
  src/Projects/Booket/Sources/AppDelegate.swift
  src/Projects/Booket/Sources/LoggingBootstrap.swift
  src/SupportingFiles/Booket/Info.plist
  src/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  src/fastlane/Fastfile
Labels: 🔨 refactor

#179 feat: 게스트 모드 추가 및 앱 흐름 변경
  src/Projects/BKData/Sources/API/BookAPI.swift
  src/Projects/BKData/Sources/Repository/DefaultAuthRepository.swift
  src/Projects/BKData/Sources/Repository/DefaultBookRepository.swift
  src/Projects/BKDomain/Sources/Entity/Book.swift
  src/Projects/BKDomain/Sources/Interface/Repository/BookRepository.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SearchBookUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultSearchBookUseCase.swift
  src/Projects/BKDomain/Sources/VO/SearchBookResult.swift
  src/Projects/BKPresentation/Sources/AppCoordinator.swift
  src/Projects/BKPresentation/Sources/ArchiveFlow/Coordinator/ArchiveCoordinator.swift
  src/Projects/BKPresentation/Sources/ArchiveFlow/View/ArchiveView.swift
  src/Projects/BKPresentation/Sources/ArchiveFlow/View/ArchiveViewController.swift
  src/Projects/BKPresentation/Sources/ArchiveFlow/View/EmptyStateView.swift
  src/Projects/BKPresentation/Sources/ArchiveFlow/ViewModel/ArchiveViewModel.swift
  src/Projects/BKPresentation/Sources/AuthFlow/Coordinator/TermsCoordinator.swift
  src/Projects/BKPresentation/Sources/Common/AccessModeCenter.swift
  src/Projects/BKPresentation/Sources/Common/AppAccessMode.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/AuthenticationRequiredNotifying.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/ErrorHandleable.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/SessionExpiredHandling.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/SessionExpiredNotifying.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/Coordinator/BookDetailCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailView.swift
  src/Projects/BKPresentation/Sources/MainFlow/BookDetail/View/BookDetailViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/Coordinator/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/ViewModel/HomeViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Coordinator/NoteCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/Coordinator/SearchCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/ViewModel/SearchViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/Coordinator/SettingCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/ViewModel/SettingViewModel.swift
  src/Projects/BKPresentation/Sources/OnboardingFlow/View/OnboardingView.swift
  src/Projects/BKPresentation/Sources/TabBarFlow/TabBarCoordinator.swift
Labels: ✨ feat

#186 feat: 기록 툴팁 추가 및 포커싱 기능 추가
  src/Projects/BKDesign/Sources/Components/TextField/BKTextFieldView.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceAppreciationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/TooltipView.swift
Labels: ✨ feat

#191 feat: 앱 버전 업데이트 기능 추가
  src/Projects/BKData/Sources/API/AppstoreAPI.swift
  src/Projects/BKData/Sources/DataAssembly.swift
  src/Projects/BKData/Sources/Repository/DefaultAppStoreRepository.swift
  src/Projects/BKDomain/Sources/DomainAssembly.swift
  src/Projects/BKDomain/Sources/Interface/Repository/AppStoreRepository.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/AppVersionUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultAppVersionUseCase.swift
  src/Projects/BKPresentation/Sources/AppCoordinator.swift
  src/Projects/BKPresentation/Sources/Common/Constant/AppStoreLinker.swift
  src/Projects/BKPresentation/Sources/Common/Constant/BKLayoutSize.swift
  src/Projects/BKPresentation/Sources/Common/Version.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/ViewModel/SettingViewModel.swift
  src/Projects/Booket/Sources/SceneDelegate.swift
Labels: ✨ feat

#197 fix: Label baseline offset 계산식 및 attribution 추가
  src/Projects/BKDesign/Sources/Components/Label/BKLabel.swift
  src/Projects/BKDesign/Sources/Components/Label/BKLabel2.swift
Labels: 🐞 fix

#204 refactor: OCR 스캐닝 방식 리팩토링
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/OCRScannerViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NLPPostprocessor.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/OCRScannerViewModel.swift
Labels: 🔨 refactor

#207 fix: 기록 상세 화면 레이아웃 이슈 해결
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/NoteCompletionView.swift
Labels: 🐞 fix
