Repository YAPP-Github/Reed-iOS, pull requests merged in 2025-07, with the labels that each got.

#52 chore: BDD 테스트 환경 구축
  src/Projects/BKCore/Project.swift
  src/Projects/BKData/Project.swift
  src/Projects/BKDomain/Project.swift
  src/Projects/BKDomain/Tests/BDDExampleTest.swift
  src/Projects/BKNetwork/Project.swift
  src/Projects/BKStorage/Project.swift
  src/Tuist/Package.resolved
  src/Tuist/Package.swift
  src/Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ⚙️ chore

#53 feat: 애플 로그인 환경 세팅
  src/Projects/BKData/Project.swift
  src/Projects/BKData/Sources/Extension/UIApplication+.swift
  src/Projects/BKData/Sources/Interface/KakaoUserAPIProtocol.swift
  src/Projects/BKData/Sources/Interface/Storage/KeyValueStorage.swift
  src/Projects/BKData/Sources/Repository/DefaultAuthRepository.swift
  src/Projects/BKData/Sources/Service/AppleLoginDelegateProxy.swift
  src/Projects/BKData/Sources/Service/AppleLoginService.swift
  src/Projects/BKData/Sources/Service/KakaoLoginService.swift
  src/Projects/BKData/Sources/ServiceImpl/AppleLoginService.swift
  src/Projects/BKDomain/Sources/Impl/DefaultSignInUseCase.swift
  src/Projects/BKDomain/Sources/Interface/SocialLoginService.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SignInUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SocialTokenAuthUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultAuthenticationWithSocialTokenUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultSocialLoginUseCase.swift
  src/Projects/BKStorage/Project.swift
  src/Projects/BKStorage/Sources/TokenStorage/KeychainKeyValueStorage.swift
Labels: ✨ feat

#55 test: 카카오 SDK API 테스트
  src/Projects/BKDomain/Sources/Error/AuthError.swift
  src/Projects/Booket/Sources/AppDelegate.swift
  src/Projects/Booket/Sources/SceneDelegate.swift
Labels: ✅ test

#68 feat: 버튼 컴포넌트 개발
  src/Projects/BKDesign/PreviewApp/Info.plist
  src/Projects/BKDesign/PreviewApp/Resources/LaunchScreen.storyboard
  src/Projects/BKDesign/PreviewApp/Sources/AppDelegate.swift
  src/Projects/BKDesign/PreviewApp/Sources/SceneDelegate.swift
  src/Projects/BKDesign/PreviewApp/Sources/View/BKButtonGroupDemoViewController.swift
  src/Projects/BKDesign/PreviewApp/Sources/View/BKButtonTestViewController.swift
  src/Projects/BKDesign/Project.swift
  src/Projects/BKDesign/Sources/Components/BKButton.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButton.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonConfiguration.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonGroup.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonProtocol.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonSize.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonState.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonStyle.swift
  src/Projects/BKDesign/Sources/Extensions/SetNeeds.swift
  src/Projects/BKDesign/Sources/Extensions/UIColor+.swift
  src/Projects/BKDesign/Sources/Extensions/UIImage+.swift
Labels: ✨ feat

#79 feat: 설정 화면 구현
  src/Projects/BKDomain/Sources/DomainAssembly.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/AppVersionUseCase.swift
  src/Projects/BKDomain/Sources/UseCase/DefaultAppVersionUseCase.swift
  src/Projects/BKPresentation/Sources/AppCoordinator.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/LoginViewController.swift
  src/Projects/BKPresentation/Sources/Common/Component/BKDividerFooterView.swift
  src/Projects/BKPresentation/Sources/Common/Constant/BKLayoutSize.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/Coordinator/SettingCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/ViewModel/SettingViewModel.swift
Labels: ✨ feat

#89 fix: 설정 화면 터치 피드백 제거
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingView.swift
Labels: 🐞 fix

#88 feat: 새로운 Navigation Style 적용
  src/Projects/BKDesign/Sources/Components/Button/BKButton.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/LoginViewController.swift
  src/Projects/BKPresentation/Sources/Common/Component/BKNavigationBarStylable.swift
  src/Projects/BKPresentation/Sources/Common/Component/BaseViewController.swift
  src/Projects/BKPresentation/Sources/Common/Extension/UINavigationController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingViewController.swift
  src/Projects/Booket/Sources/SceneDelegate.swift
Labels: ✨ feat

#92 feat: TextField 기능 추가
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/x-circle.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/x-circle.imageset/x-circle.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/x-circle.imageset/x-circle@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/icons/x-circle.imageset/x-circle@3x.png
  src/Projects/BKDesign/Sources/Components/BKBaseTextField.swift
  src/Projects/BKDesign/Sources/Components/BKSearchTextField.swift
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKIcon.swift
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKInset.swift
Labels: ✨ feat

#101 fix: 네트워크 버그 수정
  src/Projects/BKData/Sources/Repository/DefaultAuthRepository.swift
  src/Projects/BKNetwork/Sources/Helper/AuthRetrier.swift
  src/Projects/BKNetwork/Sources/NetworkAssembly.swift
  src/Projects/BKNetwork/Sources/Provider/OAuthNetworkProvider.swift
  src/Projects/BKStorage/Sources/TokenStorage/KeychainTokenProvider.swift
Labels: 🐞 fix

#102 feat: 설정 화면에 액션 연결
  src/Projects/BKDesign/PreviewApp/Sources/View/BKBottomSheetTestMenuViewController.swift
  src/Projects/BKDesign/Sources/Components/BKCheckBox.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/BKBottomSheetStyle.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/BKBottomSheetTitleView.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/BKBottomSheetViewController.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/SuppliedContentStyle.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonGroup.swift
  src/Projects/BKDesign/Sources/Components/Label/BKCheckBoxLabel.swift
  src/Projects/BKDesign/Sources/Components/Label/BKLabel.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKBaseTextField.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKSearchTextField.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextView.swift
  src/Projects/BKPresentation/Sources/AppCoordinator.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/Coordinator.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/SessionExpiredHandling.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/SessionExpiredNotifying.swift
  src/Projects/BKPresentation/Sources/MainFlow/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/Coordinator/SettingCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/View/SettingViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Setting/ViewModel/SettingViewModel.swift
Labels: ✨ feat

#103 feat: 도서 등록 Flow 추가
  src/Projects/BKDesign/Sources/Components/Button/BKButtonGroup.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/BookRegistrationStatusView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/ViewModel/SearchViewModel.swift
Labels: ✨ feat

#112 feat: 독서 기록 화면 구현
  src/Projects/BKDesign/PreviewApp/Sources/View/BKInputCatalogView.swift
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/mascot.imageset/Contents.json
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/mascot.imageset/mascot.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/mascot.imageset/mascot@2x.png
  src/Projects/BKDesign/Resources/Assets.xcassets/graphics/mascot.imageset/mascot@3x.png
  src/Projects/BKDesign/Sources/Components/BKCheckBox.swift
  src/Projects/BKDesign/Sources/Components/BKPageControl.swift
  src/Projects/BKDesign/Sources/Components/Button/BKButtonStyle.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextFieldView.swift
  src/Projects/BKDesign/Sources/Components/TextField/BKTextView.swift
  src/Projects/BKDesign/Sources/Foundation/GraphicSystem/BKImage.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/HomeViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Coordinator/NoteCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/EmotionRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceAppreciationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteForm.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/ViewModel/NoteViewModel.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchResultCell.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchViewController.swift
Labels: ✨ feat

#114 feat: 독서 기록 완료 / 기록 상세 화면 구현
  src/Projects/BKDesign/PreviewApp/Sources/View/BKDialogTestViewController.swift
  src/Projects/BKDesign/Project.swift
  src/Projects/BKDesign/Sources/Components/BottomSheet/BKBottomSheetViewController.swift
  src/Projects/BKDesign/Sources/Components/Dialog/BKDialog.swift
  src/Projects/BKDesign/Sources/Components/Dialog/BKDialogViewController.swift
  src/Projects/BKDesign/Sources/Components/Summary/BKBookSummaryView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/Coordinator/NoteCoordinator.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/EmotionRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/NoteViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceAppreciationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/Note/View/SentenceRegistrationView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/AppreciationResultView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/CollectedSentenceView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/NoteCompletionView.swift
  src/Projects/BKPresentation/Sources/MainFlow/NoteCompletion/View/NoteCompletionViewController.swift
  src/Projects/BKPresentation/Sources/MainFlow/Search/View/SearchResultCell.swift
Labels: ✨ feat

#118 fix: TabBarCoordinator 동작 및 TabBar 레이아웃 수정
  src/Projects/BKPresentation/Sources/AuthFlow/Coordinator/LoginCoordinator.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/LoginViewController.swift
  src/Projects/BKPresentation/Sources/AuthFlow/View/TermsViewController.swift
  src/Projects/BKPresentation/Sources/Common/Coordinator/FinishNotifying.swift
  src/Projects/BKPresentation/Sources/Common/Extension/UINavigationController+.swift
  src/Projects/BKPresentation/Sources/MainFlow/Home/MainFlowCoordinator.swift
  src/Projects/BKPresentation/Sources/TabBarFlow/BottomTabBarController.swift
  src/Projects/BKPresentation/Sources/TabBarFlow/TabBarCoordinator.swift
  src/Projects/BKPresentation/Sources/TabBarFlow/TabItem.swift
  src/Projects/Booket/Sources/SceneDelegate.swift
Labels: 🐞 fix
