Repository YAPP-Github/Reed-iOS, pull requests merged in 2025-06, with the labels that each got.

#18 feat: Project initialize
  src/.gitignore
  src/.mise.toml
  src/Projects/BKCore/Project.swift
  src/Projects/BKCore/Sources/Placeholder.swift
  src/Projects/BKData/Project.swift
  src/Projects/BKData/Sources/Placeholder.swift
  src/Projects/BKDesign/Project.swift
  src/Projects/BKDesign/Resources/Placeholder
  src/Projects/BKDesign/Sources/Placeholder.swift
  src/Projects/BKDomain/Project.swift
  src/Projects/BKDomain/Sources/Placeholder.swift
  src/Projects/BKNetwork/Project.swift
  src/Projects/BKNetwork/Sources/Placeholder.swift
  src/Projects/BKPresentation/Project.swift
  src/Projects/BKPresentation/Sources/Placeholder.swift
  src/Projects/BKStorage/Project.swift
  src/Projects/BKStorage/Sources/Placeholder.swift
  src/Projects/Booket/Project.swift
  src/Projects/Booket/Sources/Placeholder.swift
  src/Projects/Booket/SupportingFiles/Debug.xcconfig
  src/Projects/Booket/SupportingFiles/Release.xcconfig
  src/Tuist/Config.swift
  src/Tuist/Package.swift
  src/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  src/Tuist/ProjectDescriptionHelpers/ProjectName.swift
  src/Tuist/ProjectDescriptionHelpers/ResourceExtensions.swift
  src/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  src/Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
  src/Tuist/ProjectDescriptionHelpers/TargetDependency+Module.swift
  src/Workspace.swift
  src/hh.sh
Labels: ✨ feat, ⚙️ chore

#21 chore: swiftlint & coderabbit 세팅
  .coderabbit.yaml
  src/.swiftlint.yml
  src/Projects/BKCore/Project.swift
  src/Projects/BKData/Project.swift
  src/Projects/BKDesign/Project.swift
  src/Projects/BKDomain/Project.swift
  src/Projects/BKNetwork/Project.swift
  src/Projects/BKPresentation/Project.swift
  src/Projects/BKStorage/Project.swift
  src/Projects/Booket/Project.swift
  src/Tuist/ProjectDescriptionHelpers/SwiftLintScript.swift
  test.md
Labels: ✨ feat, ⚙️ chore, 🎨 style

#29 fix: Coderabbit 설정 변경
  .coderabbit.yaml
Labels: 🐞 fix, ✨ feat, 🎨 style

#30 chore: 자동화 로직 업데이트
  .github/workflows/create-jira-issue.yml
Labels: ✨ feat, ⚙️ chore, 🎨 style

#40 feat: 카카오 로그인 환경 세팅 및 서비스 코드 구현
  .gitignore
  src/Projects/BKData/Project.swift
  src/Projects/BKData/Sources/Interface/KakaoUserAPIProtocol.swift
  src/Projects/BKData/Sources/RepositoryImpl/DefaultAuthRepository.swift
  src/Projects/BKData/Sources/ServiceImpl/AppleLoginService.swift
  src/Projects/BKData/Sources/ServiceImpl/KakaoLoginService.swift
  src/Projects/BKDesign/Project.swift
  src/Projects/BKDomain/Project.swift
  src/Projects/BKDomain/Sources/Entity/AuthProvider.swift
  src/Projects/BKDomain/Sources/Entity/AuthTokens.swift
  src/Projects/BKDomain/Sources/Entity/SocialLoginResult.swift
  src/Projects/BKDomain/Sources/Error/AuthError.swift
  src/Projects/BKDomain/Sources/Impl/DefaultServerAuthUseCase.swift
  src/Projects/BKDomain/Sources/Impl/DefaultSignInUseCase.swift
  src/Projects/BKDomain/Sources/Impl/DefaultSocialLoginUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Repository/AuthRepository.swift
  src/Projects/BKDomain/Sources/Interface/SocialLoginService.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/DeleteAccountUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/ServerAuthUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SignInUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SignOutUseCase.swift
  src/Projects/BKDomain/Sources/Interface/Usecase/SocialLoginUseCase.swift
  src/Projects/BKDomain/Sources/Placeholder.swift
  src/Projects/BKPresentation/Project.swift
  src/Projects/Booket/Project.swift
  src/Projects/Booket/SupportingFiles/Release.xcconfig
  src/SupportingFiles/Configs/Release.xcconfig
  src/SupportingFiles/Info.plist
  src/Tuist/Package.resolved
  src/Tuist/Package.swift
  src/Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feat, 🎨 style

#42 chore: Fastlane 세팅 & workflow 구성
  .github/workflows/ios_ci.yml
  .gitignore
  src/.env.example
  src/.gitignore
  src/Gemfile
  src/Projects/BKStorage/Project.swift
  src/Projects/BKStorage/Sources/Placeholder.swift
  src/Projects/Booket/Project.swift
  src/Projects/Booket/Sources/AppDelegate.swift
  src/Projects/Booket/Sources/Placeholder.swift
  src/Projects/Booket/Sources/SceneDelegate.swift
  src/fastlane/Appfile
  src/fastlane/Fastfile
  src/fastlane/Matchfile
  src/hh.sh
  src/tuist_module_init.sh
Labels: ✨ feat, ⚙️ chore, 🎨 style
